// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcDemo25.web.Models;

#nullable disable

namespace MvcDemo25.web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121170620_AddUserIdToPerson")]
    partial class AddUserIdToPerson : AddUserIdToPersonBase
    {
    }
}
